# Generated by Django 2.2.17 on 2021-01-13 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_auto_20210107_0911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': '菜单表', 'verbose_name_plural': '菜单表'},
        ),
    ]
