# Generated by Django 2.2.17 on 2021-01-14 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='项目名')),
                ('remark', models.CharField(blank=True, max_length=128, null=True, verbose_name='备注')),
                ('status', models.CharField(choices=[(1, '正常'), (0, '禁用')], default=0, max_length=2, verbose_name='状态')),
                ('createDate', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updateDate', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': '项目表',
                'verbose_name_plural': '项目表',
            },
        ),
    ]
