# Generated by Django 2.2.17 on 2021-01-14 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='功能名')),
                ('createDate', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updateDate', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('itemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Item', verbose_name='分类ID')),
            ],
            options={
                'verbose_name': '功能表',
                'verbose_name_plural': '功能表',
            },
        ),
    ]
