# Generated by Django 2.2.17 on 2021-01-15 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_function'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='path',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='程序路劲'),
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=128, unique=True, verbose_name='主机名')),
                ('lanip', models.CharField(max_length=128, unique=True, verbose_name='主机内网IP')),
                ('wanip', models.CharField(blank=True, max_length=128, null=True, verbose_name='主机外网IP')),
                ('functionIds', models.CharField(max_length=128, verbose_name='功能列')),
                ('summary', models.TextField(verbose_name='简介')),
                ('status', models.IntegerField(choices=[(0, '已删除'), (1, '待下架'), (2, '正常'), (3, '空闲')], default=1, verbose_name='状态')),
                ('createDate', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updateDate', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('itemId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.Item', verbose_name='项目ID')),
            ],
            options={
                'verbose_name': '资产表',
                'verbose_name_plural': '资产表',
            },
        ),
    ]
