# Generated by Django 2.2.17 on 2021-01-15 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20210115_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='functionIds',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='功能列'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='hostname',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='主机名'),
        ),
        migrations.AlterField(
            model_name='function',
            name='itemId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Item', verbose_name='项目ID'),
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='功能名')),
                ('cname', models.CharField(blank=True, max_length=128, null=True, verbose_name='CNAME')),
                ('elb', models.CharField(blank=True, max_length=128, null=True, verbose_name='负载均衡')),
                ('assetIds', models.CharField(blank=True, max_length=128, null=True, verbose_name='设备列')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('createDate', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updateDate', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('itemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Item', verbose_name='项目ID')),
            ],
            options={
                'verbose_name': '域名表',
                'verbose_name_plural': '域名表',
            },
        ),
    ]
