# Generated by Django 2.2.17 on 2021-01-18 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_auto_20210118_0214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domain',
            old_name='name',
            new_name='domain_name',
        ),
    ]
