# Generated by Django 2.2.17 on 2021-01-19 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_auto_20210118_0229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domain',
            old_name='domain_name',
            new_name='name',
        ),
    ]
