# Generated by Django 2.2.17 on 2021-01-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_auto_20210119_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='owner',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='维护人'),
        ),
    ]
