# Generated by Django 2.2.17 on 2021-01-13 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20210106_0229'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '分类表', 'verbose_name_plural': '分类表'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='status',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updateDate',
        ),
        migrations.AddField(
            model_name='category',
            name='lastUpdatedTime',
            field=models.DateTimeField(auto_now=True, verbose_name='最后更新时间'),
        ),
        migrations.AlterField(
            model_name='category',
            name='sort',
            field=models.IntegerField(max_length=10, unique=True, verbose_name='排序'),
        ),
        migrations.DeleteModel(
            name='Label',
        ),
    ]
