# Generated by Django 2.2.17 on 2021-01-13 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_auto_20210113_0303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='标签名')),
                ('viewCount', models.CharField(default=0, max_length=128, verbose_name='浏览数')),
                ('thumhup', models.CharField(default=0, max_length=128, verbose_name='点赞数')),
                ('labelIds', models.CharField(max_length=128, verbose_name='标签列')),
                ('summary', models.CharField(max_length=256, verbose_name='简介')),
                ('imageUrl', models.CharField(max_length=256, verbose_name='图片链接')),
                ('mdContent', models.CharField(max_length=256, verbose_name='富文本')),
                ('htmlContent', models.CharField(max_length=256, verbose_name='html富文本')),
                ('status', models.IntegerField(choices=[(0, '已删除'), (1, '未审核'), (2, '审核通过'), (3, '审核未通过')], default=1, verbose_name='审核状态')),
                ('ispublic', models.IntegerField(choices=[(1, '公开'), (0, '不公开')], default=0, verbose_name='是否公开')),
                ('createDate', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updateDate', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': '文章表',
                'verbose_name_plural': '文章表',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'permissions': (('view_customer_list', '查看客户列表'), ('view_customer_info', '查看客户详情'), ('edit_own_customer_info', '修改客户信息')), 'verbose_name': '分类表', 'verbose_name_plural': '分类表'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='lastUpdatedTime',
            new_name='updateDate',
        ),
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[(1, '正常'), (0, '禁用')], default=0, max_length=2, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='category',
            name='sort',
            field=models.IntegerField(unique=True, verbose_name='排序'),
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='标签名')),
                ('createDate', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updateDate', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Category', verbose_name='分类ID')),
            ],
            options={
                'verbose_name': '标签表',
                'verbose_name_plural': '标签表',
            },
        ),
    ]
